CREATE DATABASE IF NOT EXISTS phonebook_boot;

USE phonebook_boot;

CREATE TABLE IF NOT EXISTS user (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	login VARCHAR(80) NOT NULL,
	password VARCHAR(100) NOT NULL,
	fio VARCHAR(100) NOT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS entry (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT UNSIGNED NOT NULL,
	surname VARCHAR(80) NOT NULL,
	name VARCHAR(80) NOT NULL,
	father_name VARCHAR(80) NOT NULL,
	mobile_number VARCHAR(30) NOT NULL,
	home_number VARCHAR(30),
	address VARCHAR(150),
	email VARCHAR(80),
	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) DEFAULT CHARSET=utf8;